<?php  

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
// $ch = curl_init();

// curl_setopt($ch, CURLOPT_URL, 'https://api.trello.com/1/boards/5f8c56ded239781510f4103f/cards/{idCard}?key=0025f95bb5bca84d5ab9d9e678e008f2&token=958dbce737ba8bd2fb261787232ef165185a189871e9e90f64ad996fe1018b64');
// curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

// $result = curl_exec($ch);
// if (curl_errno($ch)) {
//     echo 'Error:' . curl_error($ch);
// }
// curl_close($ch);

// Get Boards from here
// $ch = curl_init();

// curl_setopt($ch, CURLOPT_URL, 'https://api.trello.com/1/boards/5f8c56ded239781510f4103f?key=0025f95bb5bca84d5ab9d9e678e008f2&token=958dbce737ba8bd2fb261787232ef165185a189871e9e90f64ad996fe1018b64');
// curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
// curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


// $headers = array();
// $headers[] = 'Accept: application/json';
// curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

// $result = curl_exec($ch);
// if (curl_errno($ch)) {
//     echo 'Error:' . curl_error($ch);
// }
// curl_close($ch);

// $ch = curl_init();

// curl_setopt($ch, CURLOPT_URL, 'https://api.trello.com/1/cards?key=0025f95bb5bca84d5ab9d9e678e008f2&token=958dbce737ba8bd2fb261787232ef165185a189871e9e90f64ad996fe1018b64&idList=5f8c56ded239781510f4103f');
// curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
// curl_setopt($ch, CURLOPT_POST, 1);

// $result = curl_exec($ch);
// if (curl_errno($ch)) {
//     echo 'Error:' . curl_error($ch);
// }
// curl_close($ch);

// Get Boards from here


//print_r($result);die;
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <title>Aviandesign</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="css/responsive.css">
</head>

<body>
    <!-- dammy nav bar -->
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <nav class="navbar navbar-expand-lg navbar-light">
                    <a class="navbar-brand" href="index.html">Aviandesign</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ml-auto navbar-right text-left outo-top-crol">
                            <li class="nav-item">
                                <a class="nav-link" href="index.html">Login SignUp</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="choose-projects.html">Choose Projects</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="edit-projects.html">Edit Projects</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="dashboard.html">Dashboard</a>
                            </li>
                            <li class="nav-item active">
                                <a class="nav-link" href="admin.html">Admin Dashboard</a>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
    </div>
    <!-- dammy nav bar -->
    <!-- header -->
    <header>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="header-dashoard clearfix">
                        <h2 class="float-left">DASHBOARD</h2>
                        <div class="user-img float-right">
                            <span class="user-profile"></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- middle-dash -->
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="outer-middle-sec">
                        <div class="row">
                            <!-- left-section -->
                            <div class="col-lg-3 col-md-12">
                                <div class="admin-left-box-1">
                                    <h3>Hi, Admin</h3>
                                    <ul>
                                        <li><a class="active" href="#">Your Project</a></li>
                                        <li><a href="#">Fundoo Friday</a></li>
                                        <li><a href="#">Nawval</a></li>
                                        <li><a href="#">Project X</a></li>
                                    </ul>
                                </div>
                                <div class="admin-left-box-2">
                                    <h3>Docucments</h3>
                                    <ul>
                                        <li><span class="bold"></span><a href="#"> Qriosity Docume...</a></li>
                                        <li><span class="bold"></span><a href="#"> Snapshot Docum...</a></li>
                                    </ul>
                                </div>
                                <div class="admin-left-box-3">
                                    <h3>Assign Project</h3>
                                    <div class="clearfix">
                                        <button type="button" id="show" class="btn float-left">Invite <img
                                                src="images/admin.png"></button>
                                        <button type="button" id="show-contact" class="btn float-right">Edit Contact</button>
                                    </div>
                                </div>
                                <!-- assign-project -->
                                <div class="assign-project menu" style="display: none;">
                                    <div class="">
                                        <h3>Assign Project</h3>
                                        <form>
                                            <div class="input-group input-group-shadow mb-3">
                                                <input type="text" class="form-control"
                                                    placeholder="Add by name or email" id="projectname">
                                                <div class="input-group-append">
                                                    <span onclick="Createproject();" class="input-group-text add-user-icon"><img
                                                            src="images/add.png" alt="add-client"></span>
                                                </div>
                                            </div>
                                        </form>
                                        <h4>Clients</h4>
                                        <div class="clearfix user-deyails-pop">
                                            <div class="float-left">
                                                <span class="user-img-client"></span>
                                            </div>
                                            <div class="user-ingo">
                                                <h5>Robert</h5>
                                                <span>robertbro@gmail.com</span>
                                            </div>
                                        </div>
                                        <div class="clearfix user-deyails-pop">
                                            <div class="float-left">
                                                <span class="user-img-client"></span>
                                            </div>
                                            <div class="user-ingo">
                                                <h5>Robert</h5>
                                                <span>robertbro@gmail.com</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- add-contact -->
                                <div class="assign-project add-contact" style="display: none;">
                                    <div class="">
                                        <h3>Add Phone Number</h3>
                                        <form>
                                            <div class="input-group input-group-shadow mb-3">
                                                <input type="number" class="form-control"
                                                    placeholder="Enter Phone Number">
                                            </div>
                                            <button class="add-phone-number-done">Done</button>
                                        </form>
                                    </div>
                                </div>
                            </div>

                            <!-- left-section -->
                            <!-- right-section -->
                            <div class="col-lg-9 col-md-12">
                                <div class="progress-bar-completed">
                                    <h3>Fundoo Friday</h3>
                                    <div class="clearfix">
                                        <span class="float-left percent-completed">37 % Complete</span>
                                        <span class="float-right purecnt-hours">75 hrs / 200 hrs</span>
                                    </div>
                                    <div class="progress complted-dashboard-progress">
                                        <div class="progress-bar" role="progressbar" aria-valuenow="70"
                                            aria-valuemin="0" aria-valuemax="100" style="width:37%">
                                        </div>
                                    </div>
                                </div>
                                <div class="milestone-sec admin-padding">
                                    <h2>Milestones</h2>
                                    <div class="milestone-draft">
                                        <div class="row">
                                            <div class="col-sm-3 col-4">
                                                <div class="first-draft-text">
                                                    <h4>First Draft</h4>
                                                    <span>12-09-2020</span>
                                                </div>
                                            </div>
                                            <div class="col-sm-6 col-4">
                                                <div class="draft-progress-bar">
                                                    <div class="progress">
                                                        <div class="progress-bar" role="progressbar" aria-valuenow="70"
                                                            aria-valuemin="0" aria-valuemax="100" style="width:100%">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-sm-3 col-4">
                                                <div class="total-hours">
                                                    <span id="first-draft">50 hrs <svg width="1em" height="1em" viewBox="0 0 16 16"
                                                            class="bi bi-arrow-right-short" fill="currentColor"
                                                            xmlns="http://www.w3.org/2000/svg">
                                                            <path fill-rule="evenodd"
                                                                d="M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8z" />
                                                        </svg>
                                                    </span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- draft-1 -->
                                    <div class="milestone-draft">
                                        <div class="row">
                                            <div class="col-sm-3 col-4">
                                                <div class="first-draft-text">
                                                    <h4>Final Draft</h4>
                                                    <span>20-09-2020</span>
                                                </div>
                                            </div>
                                            <div class="col-sm-6 col-4">
                                                <div class="draft-progress-bar">
                                                    <div class="progress">
                                                        <div class="progress-bar final-draft-progress"
                                                            role="progressbar" aria-valuenow="70" aria-valuemin="0"
                                                            aria-valuemax="100" style="width:40%">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-sm-3 col-4">
                                                <div class="total-hours">
                                                    <span id="final-draft">50 hrs <svg width="1em" height="1em" viewBox="0 0 16 16"
                                                            class="bi bi-arrow-right-short" fill="currentColor"
                                                            xmlns="http://www.w3.org/2000/svg">
                                                            <path fill-rule="evenodd"
                                                                d="M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8z" />
                                                        </svg>
                                                    </span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- draft-2 -->
                                    <div class="milestone-draft">
                                        <div class="row">
                                            <div class="col-sm-3 col-4">
                                                <div class="first-draft-text">
                                                    <h4>Revisions</h4>
                                                    <span>22-09-2020</span>
                                                </div>
                                            </div>
                                            <div class="col-sm-6 col-4">
                                                <div class="draft-progress-bar">
                                                    <div class="progress">
                                                        <div class="progress-bar revision-draft-progress"
                                                            role="progressbar" aria-valuenow="70" aria-valuemin="0"
                                                            aria-valuemax="100" style="width:40%">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-sm-3 col-4">
                                                <div class="total-hours">
                                                    <span>100 hrs <svg width="1em" height="1em" viewBox="0 0 16 16"
                                                            class="bi bi-arrow-right-short" fill="currentColor"
                                                            xmlns="http://www.w3.org/2000/svg">
                                                            <path fill-rule="evenodd"
                                                                d="M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8z" />
                                                        </svg>
                                                    </span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- draft-3 -->
                                    <!-- pop-up-checkbox-first-draft -->
                                    <div class="draft-project checkbox1" style="display: none;">
                                        <div class="">
                                            <h3>First Draft</h3>
                                            <span class="hours">50 hrs</span>
                                           <div>
                                            <label class="container-box">Platform sketch
                                                <input type="checkbox" checked="checked">
                                                <span class="checkmark"></span>
                                              </label>
                                              <label class="container-box">Quriosity
                                                <input type="checkbox" checked="checked">
                                                <span class="checkmark"></span>
                                              </label>
                                              <label class="container-box">Snapshot
                                                <input type="checkbox" checked="checked">
                                                <span class="checkmark"></span>
                                              </label>
                                              <label class="container-box">Do you know your team
                                                <input type="checkbox" checked="checked">
                                                <span class="checkmark"></span>
                                              </label>
                                              <label class="container-box">Virtual Ice breaker
                                                <input type="checkbox" checked="checked">
                                                <span class="checkmark"></span>
                                              </label>
                                           </div>
                                        </div>
                                    </div>
                                    <!-- pop-up-checkbox-first-draft -->
                                    <!-- pop-up-checkbox-Final-draft -->
                                    <div class="draft-project checkbox2" style="display: none;">
                                        <div class="">
                                            <h3>Final Draft</h3>
                                            <span class="hours">50 hrs</span>
                                           <div>
                                            <label class="container-box">Platform sketch
                                                <input type="checkbox" checked="checked">
                                                <span class="checkmark"></span>
                                              </label>
                                              <label class="container-box">Quriosity
                                                <input type="checkbox" checked="checked">
                                                <span class="checkmark"></span>
                                              </label>
                                              <label class="container-box">Snapshot
                                                <input type="checkbox">
                                                <span class="checkmark"></span>
                                              </label>
                                              <label class="container-box">Do you know your team
                                                <input type="checkbox">
                                                <span class="checkmark"></span>
                                              </label>
                                              <label class="container-box">Virtual Ice breaker
                                                <input type="checkbox">
                                                <span class="checkmark"></span>
                                              </label>
                                           </div>
                                        </div>
                                    </div>
                                    <!-- pop-up-checkbox-Final-draft -->
                                </div>
                            </div>
                            <!-- right-section -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- social-connect -->
    <div class="social-connect">
        <ul>
            <li><a href="#"><img src="images/social/call.png" alt="call"></a></li>
            <li><a href="#"><img src="images/social/chat.png" alt="call"></a></li>
            <li><a href="#"><img src="images/social/mail.png" alt="call"></a></li>
        </ul>
    </div>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <script src="js/custom.js"></script>
</body>

</html>

<script>
    function Createproject(){
        var name = document.getElementById('projectname').value;
        $.ajax({
                type: "POST", 
                url:  'createproject.php',
                data: {
                "name": name
                },
                success: function(response) {
                    console.log(response);
                    alert('Project Created');
                 }
            });
    }
</script>